package com.csye.fall2018.studentInformationSystems.datamodels;

import java.util.ArrayList;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Student")
@DynamoDBDocument
public class Student {
	private String firstName;
	private String lastName;
	private String department;
	private String studentId;
	private String id;
	private ArrayList<String> registeredCourses;
	
	public Student()
	{
		
	}
	public Student(Student s)
	{
		this.firstName = s.firstName;
		this.lastName = s.lastName;
		this.department = s.department;
		this.registeredCourses = s.registeredCourses;
	}
	public Student(String studentId,String firstName,String lastName,String dept)
	{
		this.studentId = studentId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.department = dept;
		this.registeredCourses = new ArrayList<String>();
	}
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName = "firstName")
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	@DynamoDBAttribute(attributeName = "lastName")
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	@DynamoDBAttribute(attributeName = "dept")
	public String getDept() {
		return department;
	}
	public void setDept(String dept) {
		this.department = dept;
	}
	@DynamoDBIndexHashKey(attributeName = "studentId",globalSecondaryIndexName = "studentId-index")
	public String getStudentId() {
		return studentId;
	}
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	@DynamoDBAttribute(attributeName = "courseList")
	public ArrayList<String> getCoursesList() {
		return registeredCourses;
	}
	public void setCoursesList(ArrayList<String> registeredCourses) {
		this.registeredCourses = registeredCourses;
	}
	}
