package com.csye.fall2018.studentInformationSystems.datamodels;

import javax.validation.constraints.Max;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Announcements")
@DynamoDBDocument
public class Announcements {

	private String id;
	private String AnnouncementId;
	private String BoardId;
	private String AnnouncementText;

	public Announcements() {

	}

	public Announcements(String announcementId, String boardId, String announcementText) {
		this.AnnouncementId = announcementId;
		this.BoardId = boardId;
		this.AnnouncementText = announcementText;
	}

	@DynamoDBIndexRangeKey(attributeName = "AnnouncementId", globalSecondaryIndexName = "BoardId-AnnouncementId-index")
	public String getAnnouncementId() {
		return AnnouncementId;
	}

	public void setAnnouncementId(String announcementId) {
		this.AnnouncementId = announcementId;
	}

	@DynamoDBIndexHashKey(attributeName = "BoardId", globalSecondaryIndexName = "BoardId-AnnouncementId-index")
	public String getBoardId() {
		return BoardId;
	}

	public void setBoardId(String boardId) {
		this.BoardId = boardId;
	}

	@DynamoDBAttribute(attributeName = "AnnouncementText")
	@Max(160)
	public String getAnnouncementText() {
		return AnnouncementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.AnnouncementText = announcementText;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
