package com.csye.fall2018.studentInformationSystems.datamodels;

import java.util.ArrayList;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Course")
@DynamoDBDocument
public class Course {

	private String department;
	private String courseId;
	private String professorId;
	private String TAId;
	private String notificationTopic;
	private String id;
	private String boardId;
	private ArrayList<String> roster;

	public Course() {

	}

	public Course(String courseId, String dept, String professorId, String notificationTopic) {
		this.courseId = courseId;
		this.department = dept;
		this.professorId = professorId;
		this.notificationTopic = notificationTopic;
		// this.boardId = new ArrayList<String>();
		 this.roster = new ArrayList<String>();
	}

	public Course(String courseId, String dept, String professorId, String TAId, String notificationTopic) {
		this.courseId = courseId;
		this.department = dept;
		this.professorId = professorId;
		this.TAId = TAId;
		this.notificationTopic = notificationTopic;
		// this.boardId = new ArrayList<String>();
		 this.roster = new ArrayList<String>();
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "Roster")
	public ArrayList<String> getRoster() {
		return roster;
	}

	public void setRoster(ArrayList<String> roster) {
		this.roster = roster;
	}

	@DynamoDBAttribute(attributeName = "ProfessorId")
	public String getProfessor() {
		return professorId;
	}

	public void setProfessor(String professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName = "TA")
	public String getTA() {
		return TAId;
	}

	public void setTA(String tA) {
		TAId = tA;
	}

	@DynamoDBAttribute(attributeName = "Board")
	public String getBoard() {
		return boardId;
	}

	public void setBoard(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "courseId-index")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@DynamoDBAttribute(attributeName = "Department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String dept) {
		this.department = dept;
	}

	@DynamoDBAttribute(attributeName = "notificationTopic")
	public String getNotificationTopic() {
		return notificationTopic;
	}

	public void setNotificationTopic(String notificationTopic) {
		this.notificationTopic = notificationTopic;
	}
}
